INSERT INTO products (title, price, stocks) VALUES
                                               ('Wireless Bluetooth Headphones', 1499.00, 45),
                                               ('Mechanical Gaming Keyboard', 2499.00, 30),
                                               ('Wireless Mouse', 799.00, 75),
                                               ('USB-C Fast Charger', 999.00, 60),
                                               ('Laptop Stand', 1299.00, 25),
                                               ('Smart LED Bulb', 499.00, 100),
                                               ('Bluetooth Speaker', 1799.00, 40),
                                               ('USB-C Cable', 299.00, 150),
                                               ('Power Bank 20000mAh', 1899.00, 50),
                                               ('Gaming Mouse Pad', 599.00, 80),

                                               ('Webcam Full HD', 2199.00, 35),
                                               ('Laptop Backpack', 1599.00, 55),
                                               ('Wireless Earbuds', 1999.00, 65),
                                               ('Smart Watch', 2999.00, 40),
                                               ('Mobile Phone Holder', 399.00, 90),
                                               ('HDMI Cable', 449.00, 120),
                                               ('External Hard Drive 1TB', 4999.00, 20),
                                               ('USB Flash Drive 64GB', 699.00, 100),
                                               ('Portable SSD 512GB', 4499.00, 25),
                                               ('Gaming Headset', 2299.00, 35),

                                               ('Laptop Cooling Pad', 1199.00, 45),
                                               ('Smartphone Tripod', 899.00, 50),
                                               ('Wireless Charging Pad', 1299.00, 40),
                                               ('Bluetooth Keyboard', 1399.00, 35),
                                               ('USB Hub 4 Port', 799.00, 75),
                                               ('Desk Organizer', 499.00, 60),
                                               ('LED Desk Lamp', 999.00, 50),
                                               ('Digital Alarm Clock', 699.00, 45),
                                               ('Noise Cancelling Headphones', 3499.00, 30),
                                               ('Portable Bluetooth Speaker Mini', 999.00, 70),

                                               ('Smart Plug WiFi', 799.00, 55),
                                               ('Ethernet Cable Cat6', 349.00, 150),
                                               ('Laptop Sleeve 15 Inch', 899.00, 65),
                                               ('Phone Screen Protector', 199.00, 200),
                                               ('Mobile Back Cover', 299.00, 180),
                                               ('Wireless Game Controller', 2499.00, 35),
                                               ('RGB Gaming Mouse', 1299.00, 60),
                                               ('Gaming Chair', 8999.00, 15),
                                               ('Monitor Stand', 1599.00, 30),
                                               ('24 Inch LED Monitor', 8999.00, 20),

                                               ('32 Inch Smart TV', 14999.00, 15),
                                               ('Smart TV Remote', 699.00, 50),
                                               ('WiFi Router', 1899.00, 40),
                                               ('Network Switch 8 Port', 1299.00, 35),
                                               ('Bluetooth Adapter', 499.00, 90),
                                               ('Micro SD Card 128GB', 899.00, 100),
                                               ('Power Strip 6 Socket', 999.00, 70),
                                               ('Surge Protector', 799.00, 55),
                                               ('Laptop Charger 65W', 1799.00, 40),
                                               ('USB-C Docking Station', 3999.00, 25);